import anthropic
import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

# ── Config (loaded from GitHub Secrets) ──────────────────────────────────────
ANTHROPIC_API_KEY = os.environ["ANTHROPIC_API_KEY"]
GMAIL_ADDRESS     = os.environ["GMAIL_ADDRESS"]       # sender = receiver
GMAIL_APP_PASSWORD = os.environ["GMAIL_APP_PASSWORD"] # Gmail App Password


def fetch_law_updates() -> dict:
    """Ask Claude (with web search) to find 5 latest Indian law updates."""
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    prompt = """
    Search the web RIGHT NOW and find the 5 most recent and important updates 
    in Indian law, legal judgments, new legislation, or legal news from the 
    last 24-48 hours.

    Respond ONLY in this exact JSON format (no markdown, no extra text):
    {
      "email_title": "One engaging, punchy headline title for today's legal update",
      "updates": [
        {
          "heading": "Short heading for update 1",
          "points": [
            "Point 1 - specific detail",
            "Point 2 - specific detail",
            "Point 3 - specific detail",
            "Point 4 - specific detail",
            "Point 5 - specific detail"
          ]
        },
        ... (repeat for all 5 updates)
      ]
    }

    Make each update factual, specific, and useful for a legal professional in India.
    Include case names, court names, section numbers where relevant.
    """

    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=2000,
        tools=[{"type": "web_search_20250305", "name": "web_search"}],
        messages=[{"role": "user", "content": prompt}]
    )

    # Extract the text response
    import json
    for block in response.content:
        if block.type == "text":
            text = block.text.strip()
            # Strip markdown code fences if present
            if text.startswith("```"):
                text = text.split("```")[1]
                if text.startswith("json"):
                    text = text[4:]
            return json.loads(text.strip())

    raise ValueError("No text response received from Claude")


def build_html_email(data: dict, date_str: str) -> str:
    """Build a clean, professional HTML email."""
    updates_html = ""
    for i, update in enumerate(data["updates"], 1):
        points_html = "".join(f"<li>{p}</li>" for p in update["points"])
        updates_html += f"""
        <div class="update-card">
          <div class="update-number">#{i}</div>
          <h3 class="update-heading">{update['heading']}</h3>
          <ul class="points">{points_html}</ul>
        </div>
        """

    return f"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<style>
  body {{ font-family: Georgia, serif; background: #f5f0eb; margin: 0; padding: 20px; color: #2c2c2c; }}
  .wrapper {{ max-width: 640px; margin: 0 auto; }}
  .header {{ background: #1a1a2e; color: #fff; padding: 32px 28px; border-radius: 8px 8px 0 0; }}
  .header .label {{ font-size: 11px; letter-spacing: 3px; text-transform: uppercase; color: #c9a84c; margin-bottom: 10px; }}
  .header h1 {{ margin: 0; font-size: 22px; line-height: 1.4; font-weight: 700; }}
  .header .date {{ margin-top: 12px; font-size: 13px; color: #aaa; font-family: Arial, sans-serif; }}
  .body {{ background: #fff; padding: 28px; border-radius: 0 0 8px 8px; border: 1px solid #e0d8cf; border-top: none; }}
  .update-card {{ margin-bottom: 28px; padding-bottom: 24px; border-bottom: 1px solid #eee; }}
  .update-card:last-child {{ border-bottom: none; margin-bottom: 0; }}
  .update-number {{ display: inline-block; background: #c9a84c; color: #fff; font-size: 11px;
                    font-family: Arial; font-weight: bold; padding: 2px 8px; border-radius: 3px; margin-bottom: 8px; }}
  .update-heading {{ margin: 0 0 12px; font-size: 17px; color: #1a1a2e; font-weight: 700; line-height: 1.4; }}
  .points {{ margin: 0; padding-left: 18px; }}
  .points li {{ margin-bottom: 7px; font-size: 14px; line-height: 1.6; color: #444; }}
  .footer {{ text-align: center; margin-top: 20px; font-size: 12px; color: #999; font-family: Arial; }}
</style>
</head>
<body>
<div class="wrapper">
  <div class="header">
    <div class="label">⚖️ Daily Legal Update · India</div>
    <h1>{data['email_title']}</h1>
    <div class="date">{date_str}</div>
  </div>
  <div class="body">
    {updates_html}
  </div>
  <div class="footer">Auto-generated by your personal Legal Updates Assistant · Unsubscribe anytime</div>
</div>
</body>
</html>
"""


def send_email(subject: str, html_body: str):
    """Send the email via Gmail SMTP."""
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = GMAIL_ADDRESS
    msg["To"]      = GMAIL_ADDRESS
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
        server.sendmail(GMAIL_ADDRESS, GMAIL_ADDRESS, msg.as_string())
    print("✅ Email sent successfully!")


def main():
    date_str = datetime.now().strftime("%A, %d %B %Y")
    print(f"Fetching Indian law updates for {date_str}...")

    data = fetch_law_updates()
    print(f"Title: {data['email_title']}")

    html  = build_html_email(data, date_str)
    subj  = f"⚖️ Daily Law Update – {date_str}"
    send_email(subj, html)


if __name__ == "__main__":
    main()
